/* Generated By:JavaCC: Do not edit this line. ReadplaatsingConstants.java */
package placement.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReadplaatsingConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NF = 6;
  /** RegularExpression Id. */
  int AF = 7;
  /** RegularExpression Id. */
  int AS = 8;
  /** RegularExpression Id. */
  int X = 9;
  /** RegularExpression Id. */
  int LB = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int Id = 12;
  /** RegularExpression Id. */
  int Idn = 13;
  /** RegularExpression Id. */
  int Filename = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"Netlist file:\"",
    "\"Architecture file:\"",
    "\"Array size:\"",
    "\"x\"",
    "\"logic blocks\"",
    "<NUMBER>",
    "<Id>",
    "<Idn>",
    "<Filename>",
  };

}
