/* Generated By:JavaCC: Do not edit this line. ReadnetlistConstants.java */
package circuit.parser.netlist;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReadnetlistConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 6;
  /** RegularExpression Id. */
  int OUT = 7;
  /** RegularExpression Id. */
  int CLB = 8;
  /** RegularExpression Id. */
  int CON = 9;
  /** RegularExpression Id. */
  int GLO = 10;
  /** RegularExpression Id. */
  int PINLIST = 11;
  /** RegularExpression Id. */
  int SOURCELIST = 12;
  /** RegularExpression Id. */
  int SINKLIST = 13;
  /** RegularExpression Id. */
  int NET = 14;
  /** RegularExpression Id. */
  int SCHEME = 15;
  /** RegularExpression Id. */
  int SUBBLOCK = 16;
  /** RegularExpression Id. */
  int OPEN = 17;
  /** RegularExpression Id. */
  int Id = 18;
  /** RegularExpression Id. */
  int Idn = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\".input\"",
    "\".output\"",
    "\".clb\"",
    "\".con\"",
    "\".global\"",
    "\"pinlist:\"",
    "\"sourcelist:\"",
    "\"sinklist:\"",
    "\"net:\"",
    "\"scheme:\"",
    "\"subblock:\"",
    "\"open\"",
    "<Id>",
    "<Idn>",
    "<NUMBER>",
  };

}
